package top.bogey.touch_tool_pro.bean.pin;

public enum PinSubType {
    NORMAL,

    DATE, TIME, PERIODIC,

    MULTI_LINE,

    URL, SHORTCUT,

    NODE_ID, RINGTONE,

    SINGLE, SINGLE_ACTIVITY, SINGLE_ALL_ACTIVITY, MULTI, MULTI_ACTIVITY, MULTI_ALL_ACTIVITY, SHARE_ACTIVITY
}
